# Generated by Django 2.1.4 on 2019-01-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=20)),
                ('tipo_despesa', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=50)),
                ('forma_pagamento', models.CharField(max_length=10)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
