# Generated by Django 2.1.4 on 2019-01-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], max_length=10),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('Remédio', 'Remédio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=30),
        ),
    ]
