# Generated by Django 2.1.4 on 2019-01-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190103_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.CharField(max_length=20, verbose_name='data de criacao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], max_length=50, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('Remédio', 'Remédio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=30, verbose_name='tipo de despesa'),
        ),
    ]
