# Generated by Django 2.1.4 on 2019-01-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190104_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data_atual',
        ),
    ]
